image: Visual Studio 2017

install:
  - ps: $Env:FRFUEL_VERSION = Get-Content version.txt -Raw

artifacts:
  - path: frfuel_$(FRFUEL_VERSION).zip
    name: frfuel

configuration: Release
platform: Any CPU

before_build:
- nuget restore

build:
  project: FRFuel.sln

after_build:
- 7z a frfuel_%FRFUEL_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\dist\*
- 7z a frfuel_%FRFUEL_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\bin\Release\frfuel.net.dll
